#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [[ $# -eq 0 ]]; then
    for v in 3.8 3.9; do
        docker push "${DOCKER_REPO}:$v"
    done
    docker push "${DOCKER_REPO}:latest"
else
    docker push "$@"
fi
