name: Publish Docker image
on: [push]
jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9, latest]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: pyversion=${{ matrix.python }}
          tags: anyakichi/pipenv-builder:${{ matrix.python }}
